### ISSUE TITLE
Allow multiple file extensions 

### ISSUE THREAD

**Issue by tofias** [SimonSapin/Flask-FlatPages#33]
FLATPAGES_EXTENSION should allow for a list instead of a single extension. Please forgive my very hacky, hacky solution, but something like this:

        def _walk(directory, path_prefix=()):
            """Walk over directory and find all possible flatpages, files which
            ended with ``FLATPAGES_EXTENSION`` value.
            """
            for name in os.listdir(directory):
                full_name = os.path.join(directory, name)

                if os.path.isdir(full_name):
                    _walk(full_name, path_prefix + (name,))
                # Loop through all extensions for each file.
                else:
                    for extension in extensions: 
                        if name.endswith(extension):
                            name_without_extension = name[:-len(extension)]
                            path = u'/'.join(path_prefix + (name_without_extension, ))
                            pages[path] = self._load_file(path, full_name)

        # Extensions plural.
        extensions = []
        if isinstance(self.config('extension'), basestring):
            extensions.append(self.config('extension'))
        else:
            extensions = self.config('extension')

**Comment by playpauseandstop** [comment]
Thanks for idea! Will add support of mutliple file extensions in upcoming release!

**Comment by tofias** [comment]
Thanks, I have found this to be quite handy.
