### ISSUE TITLE
The page parser should be more forgiving.

### ISSUE THREAD

**Issue by tofias** [SimonSapin/Flask-FlatPages#34]
Okay, if you thought my last issue and solution were crummy you are sure to think this is much worse. in the _parse function I would suggest along these lines before html_renderer:

        # If there is not meta + content is it meta or content or both?
        if content is None or content == '':
            lines = meta.split('\n')
            _wordcolon = re.compile('[a-z].*\:')
            # If first word in meta is not followed by a colon, it's not meta.
            if not _wordcolon.match(lines[0]):
                content = meta
                meta = u'metadata: nada'

            # If meta and content exist but aren't separated, split them
            else: 
                _addbreaks = re.compile('\n')
                string = _addbreaks.sub(u'\n\n', meta)
                _removebreaks = re.compile('\\n([a-z_1-9\-].*(?!\\:))')
                string = _removebreaks.sub('\\1', string)
                meta = u''
                lines = iter(string.split('\n'))
                meta = u'\n'.join(itertools.takewhile(unicode.strip, lines))
                content = u'\n'.join(lines)

Hey, someday maybe I will learn to make beautiful code and submit awesome pull requests, but until then please don't get too mad at me. Thanks ;-)

**Comment by playpauseandstop** [comment]
I'm not sure here. Let's discuss if we really need adding magic for splitting metadata and page content. 

From my point of view current solution is pretty clear and simple, separate page metadata and content with two empty lines and good things happen :)

**Comment by tofias** [comment]
I think you are probably right. In part, I've learned a little bit more about yaml and I understand my very simplistic approach isn't nearly sophisticated enough to do the job well.

However, this was a problem my users were having frequently, but maybe it is a problem I should let them have b/c they will have it once or twice or whatever and then learn to tap return and never experience a problem again?

**Comment by playpauseandstop** [comment]
Closed for now. Think that current approach is good enough.
