### ISSUE TITLE
How to use Markdown extension attributes

### ISSUE THREAD

**Issue by willwade** [SimonSapin/Flask-FlatPages#37]
So I want to use Markdown extension TOC - http://pythonhosted.org/Markdown/extensions/toc.html. I've added toc to the list of extensions and expecting to put page.toc in my template but no luck. Any tips on actually prnting the TOC into the body of the page??

**Comment by arjunblj** [comment]
Yeah, I ran into something similar because I wanted to use footnotes. I'm happy to take a shot at implementing this. @playpauseandstop – did you have any thoughts on this?

**Comment by tofias** [comment]
Footnotes works fine. To your configuration add something like:

```FLATPAGES_MARKDOWN_EXTENSIONS = ['footnotes(UNIQUE_IDS=True)']```

**Comment by arjunblj** [comment]
That was perf, thanks!

**Comment by playpauseandstop** [comment]
@willwade 

Just add ``'toc'`` to list of supported Markdown extensions and everything should work properly, e.g.

    FLATPAGES_MARKDOWN_EXTENSIONS = ['codehilite', 'toc']

Example available in [tests](https://github.com/SimonSapin/Flask-FlatPages/blob/e6249d9fe8be1d12d5a136900db61a86e5fbb235/testapp/tests.py#L221)

**Comment by playpauseandstop** [comment]
Also added note about passing arguments to Markdown extensions to docs. Thanks @tofias!

**Comment by colmoneill** [comment]
I'm sorry to be commenting on a closed issue, but it seems like only half of the original question has been answered, I'm interested in the second part of @willwade question: how to include a specific item emerging from an extension in the template ? Exactly in the same case as the original issue;

I'd like to have an object I can pass to my templates containing only the TOC of the MD.

Is there any way of doing this ?

Thanks !
