### ISSUE TITLE
Release a python3-compatible version?

### ISSUE THREAD

**Issue by sloria** [SimonSapin/Flask-FlatPages#40]
I see that the 0.6 release line will bring support for Python 3. Just wondering: is there a plan for releasing this?

**Comment by playpauseandstop** [comment]
I'll try to do my best, find time and release 0.6 with Python 3 support on next week. Missing Python 3 version really annoys!

**Comment by sloria** [comment]
@playpauseandstop Thanks! I appreciate it.

**Comment by playpauseandstop** [comment]
Setting up milestone for 0.6 at next Friday, but hope that be able to release new version earlier as there not many feature requests to do in 0.6

**Comment by Pephers** [comment]
Hi @playpauseandstop, is there any update on a 0.6 release with Python 3 support? Thanks!

**Comment by playpauseandstop** [comment]
@Pephers 

0.6 version with 3.3 and 3.4 support would be released later today, sorry for delay

**Comment by playpauseandstop** [comment]
Flask-FlatPages 0.6 released on PyPI. Now it works on Python 3.3+ as well as Flask does.

Thanks everyone for waiting this release!

**Comment by Pephers** [comment]
That's awesome! Thanks for your great work, @playpauseandstop.
