### ISSUE TITLE
Markdown extra not working.

### ISSUE THREAD

**Issue by macgera** [SimonSapin/Flask-FlatPages#42]
Some time i need render markdown inside html... But `extra` extension not working.

    <div markdown="1">
         This is *true* markdown text.
    </div>

render: This is *true* markdown text.

In my file include extra extension.  https://github.com/macgera/macgera/blob/master/src/app.py#L21

What i do wrong?

**Comment by playpauseandstop** [comment]
I'm not sure, what could be wrong. Added simple test to show that Markdown extra extension works as expected from [docs](https://pythonhosted.org/Markdown/extensions/extra.html).

So I can only recommend to check [Markdown](https://warehouse.python.org/project/Markdown/) requirement version and make sure that rendered output is really not what you expect.

**Comment by macgera** [comment]
I am update markdown to 2.6.2 and update flask flatpages to 0.6 and works fine! Awesome! Anyway tnx a lot.

**Comment by playpauseandstop** [comment]
Great!

Closes #42
