### ISSUE TITLE
Extensions list can contain objects

### ISSUE THREAD

**Issue by cyborgizator** [SimonSapin/Flask-FlatPages#45]
https://github.com/SimonSapin/Flask-FlatPages/blob/master/flask_flatpages/utils.py#L45 causes error if markdown extensions list contains non-strings (markdown allows to store extension object in the list). As a quick dirty fix the following code (utils.py, line 45) can be used:

    if str(extension).startswith('codehilite'):

**Comment by playpauseandstop** [comment]
Thanks for reporting, will fix shortly
